### ISSUE TITLE
Using this lib without require

### ISSUE THREAD

**Issue by ghost** [kchapelier/SimpleMidiInput.js#4]
Any possibility to use this without require and instantiate this in a .js front end page?
I am not able to call this library the way the examples say.
Best, Luis

(using var smi = new SimpleMidiInput();)

**Comment by kchapelier** [comment]
Yes, absolutely. There is a generic/UMD build in the build/ folder of the repo. You can also use wzrd.in to compile and minify a build for you (it works with any npm package) : https://wzrd.in/standalone/simple-midi-input@latest (save the file locally, I do not recommend using this service as a CDN as it is sometimes down)

Include one or the other as a `<script src=""></script>` element and `SimpleMidiInput` will be globally accessible in your page/application.

**Comment by ghost** [comment]
Thank you very much!
Best, Luis
