### ISSUE TITLE
Broken in latest chrome due to Iterator toString output change

### ISSUE THREAD

**Issue by 1j01** [kchapelier/SimpleMidiInput.js#6]
`Object.prototype.toString.call(value)` now gives `'[object MIDIInputMap Iterator]'` in Chrome, as of Version 110.0.5481.77 (possibly a bit earlier.)

The `isIterator` function in SimpleMidiInput currently checks against the exact string `'[object Iterator]'`.
This leads to no inputs being attached, and no notes being received.

Changing `isIterator` to check properly (using the iterable protocol, as they call it) fixes the problem:
```js
var isIterator = function (value) {
    return Symbol.iterator in Object(value);
};
```

That said, this code:
```js
        if (isArray(source)) {
            inputs = source;
        } else if (isIterator(source)) {
            while (input = source.next().value) {
                inputs.push(input);
            }
        }
```
Could be replaced with:
```js
        inputs = Array.from(source);
```
...eliminating two type checking functions, and I question the need for the others.

**Comment by kchapelier** [comment]
Hello, thank you for the head up. I'll look into it ~later tonight (CET time).~ tomorrow night (CET time).

> [...] and I question the need for the others.

There have been **_so many_** changes and incompatibilities between browser regarding the WebMidi API, all of those checks and conditions were sensible at some times. I'll keep them until I somehow decide to make a new major version..

**Comment by kchapelier** [comment]
The issue is fixed.

Went for a minimalist patch which should not break compatibility for any legacy browser. I may do a complete revamp of the lib in the coming weeks to modernize and simplify the code by only supporting the current WebMidi implemention among other things.

Getting this dev environment to work after 8y was interesting..

**Comment by 1j01** [comment]
Sounds good. Thanks for the library! It was helpful in getting [midi-recorder.web.app](https://midi-recorder.web.app/) off the ground — which you should check out, by the way. It's the easiest way to record MIDI that I've ever seen, because you don't even have to hit record.
